### ISSUE TITLE
Timeout on macOS

### ISSUE THREAD

**Issue by mzaharie** [sublimelsp/LSP-SonarLint#11]
> Failed to start SonarLint - disabling for this window for the duration of the current session.
> Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette.

> --- Error: ---
> timed out

From console:
```
Unable to start subprocess for SonarLint
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 266, in start_async
    transport = create_transport(transport_config, transport_cwd, session)
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 258, in create_transport
    start_subprocess
  File "/Users/user/Library/Application Support/Sublime Text/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 364, in _await_tcp_connection
    sock, _ = listener_socket.accept()
  File "./python3.3/socket.py", line 135, in accept
socket.timeout: timed out
```

**Comment by cb-oura** [comment]
Same issue here

**Comment by ibc** [comment]
Same problem. Ok, abandoned project.

**Comment by rwols** [comment]
It’s open source, so you are free to experiment with getting things up and running, of course.

**Comment by ibc** [comment]
It can be open source and abandoned or unmaintained at the same time. Nothing wrong here.

**Comment by rchl** [comment]
It's true, we don't have anyone who would maintain it. That's why it's not even made available in Package Control.
