### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by smileBeda** [sublimelsp/LSP-SonarLint#8]
I installed Java, then the LSP SonarLinter, when saving a file it throws:
```
Failed to start SonarLint - disabling for this window for the duration of the current session.
Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette.

--- Error: ---
timed out
```

Full console stack:
```
startup, version: 4126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/sublime_text
application: /Applications/Sublime Text.app
working dir: /
packages path: .../Library/Application Support/Sublime Text 3/Packages
state path: .../Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: .../Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
top level value must be an array
pre session restore time: 0.336328
OpenGL Context Information:
  GL API Version: 4.1 INTEL-18.7.4
  GLSL Version: 4.10
  Vendor: Intel Inc.
  Renderer: Intel(R) UHD Graphics 630
startup time: 0.438661
first paint time: 0.546832
git: using configuration from system git install
git: tracking working dir .../.../.../Project
environment variables loaded using: /bin/zsh -l
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading plugin Default.arithmetic
reloading python 3.3 plugin 0_package_control_loader.50-backrefs
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading python 3.3 plugin 0_package_control_loader.50-bracex
reloading python 3.3 plugin 0_package_control_loader.50-pathlib
reloading plugin Default.colors
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading python 3.3 plugin 0_package_control_loader.55-mdpopups
reloading python 3.3 plugin 0_package_control_loader.55-wcmatch
reloading python 3.3 plugin LSP-SonarLint.plugin
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading python 3.3 plugin LSP.boot
reloading python 3.3 plugin Package Control.1_reloader
reloading python 3.3 plugin Package Control.2_bootstrap
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin Phpcs.phpcs
reloading python 3.3 plugin wpseek WordPress Developer Assistant.sublime-text-2-wpseek
reloading python 3.3 plugin Tabnine.TabNine
Tabnine: starting version .../Library/Application Support/Sublime Text 3/Packages/Tabnine/lib/../binaries/4.4.71
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2022-07-16 06:58:48, next run at 2022-07-16 07:58:48 or after
Unable to start subprocess for SonarLint
Traceback (most recent call last):
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 266, in start_async
    transport = create_transport(transport_config, transport_cwd, session)
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 251, in create_transport
    start_subprocess
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/transports.py", line 357, in _await_tcp_connection
    sock, _ = listener_socket.accept()
  File "./python3.3/socket.py", line 135, in accept
socket.timeout: timed out
```

**Comment by sexybiggetje** [comment]
Did you clone the repo? The release file contains the jar files. If I extract those first this issue won't appear for me.

**Comment by smileBeda** [comment]
@martijndeb where does the cloned release go to?
Why is this not - like anything else in sublime text packages - done automatically?
Why is this not in the Readme?

It sounds fishy that I have to manually download or clone the release, and then put it (where?).

**Comment by smileBeda** [comment]
Putting the release into the Sublime Text 3 > Packages folder seems to have resolve that error.

Frustrating that this is not mentioned anywhere and remains a variable that no one knows if it is even needed.

**Comment by smileBeda** [comment]
Amazing. No more JAR files included in the cloned git or whatever. I am not a specialist of Sublime Text packages, but now not even anymore cloning the package to the packages will work
Latest release is of 2020, latest commit of 2022

What a mess.
